use std::{env, fmt::Write, path::PathBuf};

use wgsl_to_wgpu::{create_shader_module, MatrixVectorTypes, WriteOptions};

fn main() {
    let mut text = String::new();
    writeln!(&mut text, "// File automatically generated by build.rs.").unwrap();
    writeln!(&mut text, "// Changes made to this file will not be saved.").unwrap();
    for name in ["scan_image", "copy_texture"] {
        println!("cargo:rerun-if-changed=src/scan_view/{name}.wgsl");
        writeln!(&mut text, "pub mod {name}{{").unwrap();
        let wgsl_source = std::fs::read_to_string(
            PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap())
                .join(format!("src/scan_view/{name}.wgsl")),
        )
        .unwrap();

        std::fs::write(
            format!("{}/{name}.wgsl", env::var("OUT_DIR").unwrap()),
            wgsl_source.as_bytes(),
        ).unwrap();

        // Generate the Rust bindings and write to a file.
        let mut src = create_shader_module(
            &wgsl_source,
        &format!("{}/{name}.wgsl", env::var("OUT_DIR").unwrap()),
            WriteOptions {
                derive_bytemuck_vertex: true,
                derive_bytemuck_host_shareable: true,
                matrix_vector_types: MatrixVectorTypes::Glam,
                rustfmt: true,
                derive_encase_host_shareable: false,
                derive_serde: false,
                validate: Some(Default::default()),
            },
        )
        .unwrap()
        .replace(
            "pub struct BindGroup0(eframe::wgpu::BindGroup)",
            "pub struct BindGroup0(pub eframe::wgpu::BindGroup)",
        );
        text += &src;

        writeln!(&mut text, "}}").unwrap();
    }
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    std::fs::write(out_path.join("shader_bindings.rs"), text.as_bytes()).unwrap();
}
