[package]
name = "scan_control"
version = "0.1.0"
edition = "2021"

[profile.dev]
incremental = true  # default, but set explicitly
codegen-units = 256 # faster recompile, slower runtime

[dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }
env_logger = "0.11"
eframe = { workspace = true, features = ["wgpu"] }
egui = { workspace = true, features = ["mint", "bytemuck"] }
# egui-colorgradient = { path = "../egui-colorgradient/egui-colorgradient" }
glam = { workspace = true, features = ["mint", "bytemuck", "zerocopy"] }
mint = "0.5.9"
itertools.workspace = true
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.18", features = ["v4"] }
image-compute = { path = "crates/image-compute" }
sxmfile = { path = "crates/sxmfile" }
notify-typed = { path = "crates/notify-typed" }
filetree = { path = "crates/filetree" }
wgpu = { workspace = true, default-features = false, features = ["wgsl"] }
bytemuck.workspace = true
eyre.workspace = true
tracing.workspace = true
smol.workspace = true
egui-file-dialog = "0.11.0"
egui_extras = { version = "0.32", features = ["image"] }
id_tree = "1.8.0"
thiserror = "2.0.17"
borrow = "2.0.0"
nanonis-tcp = { path = "../nanonis-tcp"}
parking_lot = "0.12.5"
image.workspace = true
nalgebra = "0.34.1"
float-ord = "0.3.2"
gdsr = "0.0.1-alpha.3"
zerocopy.workspace = true

[build-dependencies]
wgsl_to_wgpu.workspace = true

[dev-dependencies]
pollster = "0.4.0"

[workspace]
members = [
    "crates/sxmfile",
    "crates/image-compute",
    "crates/notify-typed",
    "crates/filetree",
]

[workspace.dependencies]
zerocopy = "0.8.48"
image = "0.25.10"
bytemuck = "1.20"
itertools = "0.14"
wgpu = { version = "25.0", default-features = false } # need to use 25.0 because of egui
wgsl_to_wgpu = "0.15.0" # latest version that uses wgpu 25.0
eyre = "0.6"
tracing = "0.1"
smol = "2.0.2"
tracing-subscriber = "0.3"
glam = "0.32"
eframe = "0.32"
egui = "0.32"
