use std::{env, fmt::Write, path::PathBuf, process::Command};

use wgsl_to_wgpu::{create_shader_module, MatrixVectorTypes, WriteOptions};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    compile_rust_shaders()?;
    generate_wgsl_bindings("plane_fit", "plane_fit", |_| {})?;
    // generate_wgsl_bindings("plane_fit", "plane_fit_32", |src| {
    //     *src = src
    //         .lines()
    //         .map(|s| s.replace("f64", "f32"))
    //         .fold(String::new(), |a, b| a + &b + "\n");
    // })?;
    generate_wgsl_bindings("scan_image", "scan_image", |_| {})?;
    generate_wgsl_bindings("file_image", "file_image", |_| {})?;
    generate_wgsl_bindings("border_line", "border_line", |_| {})?;
    Ok(())
}

fn compile_rust_shaders() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let builder_dir = manifest_dir.join("shader-builder");
    let shader_dir = manifest_dir.join("shader");
    let output =
        PathBuf::from(env::var_os("OUT_DIR").ok_or("OUT_DIR is not set")?).join("hello_world.spv");
    let helper_target = output.parent().unwrap().join("rust-gpu-builder-target");

    println!("cargo:rerun-if-changed={}", shader_dir.display());
    println!("cargo:rerun-if-changed={}", builder_dir.display());
    println!("cargo:rerun-if-env-changed=RUST_GPU_TOOLCHAIN_BIN");

    // On regular Linux and Windows installations, rustup's Cargo proxy reads
    // the builder crate's rust-toolchain.toml and selects the required nightly.
    // Nix instead supplies a real Cargo binary from the same pinned toolchain.
    let nix_toolchain = env::var_os("RUST_GPU_TOOLCHAIN_BIN");
    let mut command = Command::new("cargo");
    command
        .current_dir(&builder_dir)
        .args(["run", "--quiet", "--release", "--locked", "--target-dir"])
        .arg(helper_target)
        .arg("--")
        .arg(&shader_dir)
        .arg(&output);

    // Nix supplies the pinned toolchain directly. On rustup-based Linux and
    // Windows setups, the builder's local rust-toolchain.toml selects it.
    if let Some(bin_dir) = nix_toolchain {
        let mut paths = vec![PathBuf::from(bin_dir)];
        paths.extend(env::split_paths(&env::var_os("PATH").unwrap_or_default()));
        command.env("PATH", env::join_paths(paths)?);
        command.arg("--nix-toolchain");
    }

    let status = command.status()?;
    if !status.success() {
        return Err(format!("rust-gpu shader build failed with {status}").into());
    }
    Ok(())
}

fn generate_wgsl_bindings(
    src: &str,
    output: &str,
    preprocess: impl FnOnce(&mut String),
) -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=shaders/{src}.wgsl");
    let wgsl_file = format!("shaders/{src}.wgsl");
    let mut wgsl_source = std::fs::read_to_string(&wgsl_file)?;
    preprocess(&mut wgsl_source);

    std::fs::write(
        format!("{}/{output}.wgsl", env::var("OUT_DIR")?),
        wgsl_source.as_bytes(),
    )?;

    // Generate the Rust bindings and write to a file.
    let mut text = String::new();
    writeln!(&mut text, "// File automatically generated by build.rs.")?;
    writeln!(&mut text, "// Changes made to this file will not be saved.")?;

    text += &create_shader_module(
        &wgsl_source,
        &format!("{}/{output}.wgsl", env::var("OUT_DIR")?),
        WriteOptions {
            derive_bytemuck_vertex: true,
            derive_encase_host_shareable: false,
            matrix_vector_types: MatrixVectorTypes::Glam,
            rustfmt: true,
            validate: Some(Default::default()),
            derive_bytemuck_host_shareable: true,
            ..Default::default()
        },
    )
    .inspect_err(|error| error.emit_to_stderr_with_path(&wgsl_source, &wgsl_file))
    .map_err(|_| "Failed to validate shader")?;

    std::fs::write(
        format!("{}/{output}.rs", env::var("OUT_DIR")?),
        text.as_bytes(),
    )?;
    Ok(())
}
