[package]
name = "image-compute"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = {workspace = true, features = ["encase"]}
bytemuck.workspace = true
itertools.workspace = true
thiserror = "2.0"
tracing.workspace = true
wgpu = { workspace = true, features = ["wgsl"] }
egui.workspace = true
eframe.workspace = true
parking_lot = "0.12.5"
image.workspace = true
encase = "0.12"

[build-dependencies]
wgsl_to_wgpu.workspace = true

[dev-dependencies]
wgpu = { workspace = true, features = ["wgsl", "dx12", "metal", "vulkan"] }
eframe = { workspace = true, features = ["wgpu"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
eyre.workspace = true
smol.workspace = true
